name: Keep my Duolingo streak
author: "Thành Long - William"
description: "This action will keep your Duolingo streak."

branding:
  icon: book-open
  color: green

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
      run: |
        node index.js
      env:
        DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
        LESSONS: "10"
